[platformio]
default_envs = opendual

[env:opendual]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
platform_packages =
  platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b
  espressif/toolchain-xtensa-esp32@8.4.0+2021r2-patch5
  platformio/tool-esptoolpy@1.40501.0
  platformio/tool-scons@4.40801.0
board_build.flash_size = 4MB
board_build.partitions = default.csv
monitor_speed = 115200
extra_scripts = pre:scripts/generate_pins.py
build_flags =
  ${common.build_flags}
  -D ODR_MODE=0
lib_ldf_mode = deep+

[common]
build_flags =
  -D CORE_DEBUG_LEVEL=0
  -D OPT_OSDP_PD_ONLY
  -D OPT_OSDP_APP_OWNED_QUEUE_DATA

[env:wiegand]
extends = env:opendual
build_flags =
  ${common.build_flags}
  -D ODR_MODE=1

[env:standalone]
extends = env:opendual
build_flags =
  ${common.build_flags}
  -D ODR_MODE=2

[env:provision]
extends = env:opendual
build_flags =
  ${env:opendual.build_flags}
  -D ODR_PROVISIONING_IMAGE=1
